version: 0.2

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
      - sudo yum -y install unzip
      - unzip terraform_1.1.8_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - terraform version
  pre_build:
    commands:
      - git clone https://$GIT_USER:$GIT_PASS@$GIT_REPO
  build:
    commands:
      - cd $GIT_REPO_NAME
      - terraform init
      - terraform apply -auto-approve